### ISSUE TITLE
todo of `jstransformer-absurd`

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-absurd#1]
- update readme with sample usage example
- examples and demos

**Comment by RobLoach** [comment]
> update readme with sample usage example

Available in the revamp PR: https://github.com/jstransformers/jstransformer-absurd/blob/revamp/README.md

> examples and demos

Not sure it's needed. If we want more examples/demos, then we should send them upstream to the AbsurdJS project rather than here.
